project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Marco Guerra
    right:
      - href: Talks.qmd
        text: CV
      - href: blog/index.qmd
        text: Blog
      - icon: github
        href: https://github.com/marco-gue
    
      
format:
  html:
    fontsize: 20px
    theme: [cosmo, styles.scss]

