project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: Home
        href: index.qmd
      
format:
  html:
    backgroundcolor: rgba(255, 99, 71, 0.4)
    fontcolor: "white"
    linkcolor: "black"
    mainfont: "sarif"
    fontsize: 20px
    theme: [cosmo, styles.scss]

